---

fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "firewall": "https://github.com/puppetlabs/puppetlabs-firewall"
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
  symlinks:
    "bdii": "#{source_dir}"

